### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by tylerdmace** [chaincodelabs/bitcoin-perfmonitor#5]
Any areas that you could use some extra hands with?

**Comment by MarcoFalke** [comment]
Some ideas:

* I just realized we compile twice (once to check memory usage with `-j 1` and then again with larger `-j` to check time). Imo we could do both in the same step with `-j 1`
* Also the `-reindex` should measure memory usage, I think

**Comment by MarcoFalke** [comment]
Also thanks for working on this. This is a very new project and needs helping hands.

**Comment by MarcoFalke** [comment]
I fixed my suggestion in #7

@jamesob Do you have any other projects to work on? Otherwise, I'd suggest to close this for now.

**Comment by jamesob** [comment]
@tylerdmace thanks for the offer! I'll keep you posted if I think of anything - most of our work now is going to be in provisioning the dedicated infrastructure for running the benchmarks and ensuring the existing benchmarks are stable. Otherwise, try thinking of measures that you think are important to keep tabs on but aren't already reflected in the runner.
